baseURL = "https://kathrynwantlin.com/"

# set your your own ga token here.
googleAnalytics = "UA/G-123123-12"

languageCode = "en-us"

# for using avicenna you need to set the themes to 'avicenna'
enableEmoji = true
theme = "avicenna"

# This is your page title, it appears in your tab
title = "Kathryn Wantlin"

# number of posts to show on the blog page
paginate = 10

[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.51"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[markup]
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 1

[params]
# it is used for the copy-right section of your page
name = "Kathryn Wantlin"
